# Uncomment the next line to define a global platform for your project
 platform :ios, '10.2'

target 'BNPayment-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for BNPayment-Example
  pod 'APAC-BNPayment', :path => '../'
  pod 'CardIO', '~> 5.4.1'
end
